version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8 
    working_directory: ~/repo

jobs:
  test:
    executor: python-executor
    steps:
      - checkout 
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt  # Make sure to create a requirements.txt file
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest tests.py  

workflows:
  version: 2
  test:
    jobs:
      - test
